// Generate one curated fork per group (group-a … group-l) as a JSON seed in the
// repo. Each is a hand-written conversation — a simple question and a short
// answer plus the group's standings widget — with no agent call, so the answer
// stays terse. The widget self-fetches live data from its letter alone, so the
// tool output can be minimal. Move these into the Blob store later; the JSON
// shape matches exactly what saveFork writes.
//
//   bun run lib/forks/seed-groups.ts

import { mkdirSync, writeFileSync } from "node:fs";
import { type GroupLetter, groupLetters } from "../tournament";
import type { ForkSeed } from "./store";

// Fixed so re-runs don't churn the committed files.
const CREATED_AT = "2026-06-27T00:00:00.000Z";
const OUT_DIR = new URL("./seeds/", import.meta.url);

type StreamEvent = ForkSeed["events"][number];

// The minimal event sequence the message reducer turns into: a user message,
// then an assistant turn that calls show_group_standings (→ widget) and ends
// with one short line of text.
function groupEvents(letter: GroupLetter): StreamEvent[] {
  const turnId = `seed-group-${letter.toLowerCase()}`;
  const callId = `${turnId}-show`;
  const question = `How is group ${letter} going?`;
  const answer = `Here is Group ${letter}:`;

  return [
    {
      type: "message.received",
      data: { message: question, sequence: 0, turnId },
    },
    { type: "step.started", data: { sequence: 1, stepIndex: 0, turnId } },
    {
      type: "actions.requested",
      data: {
        actions: [
          {
            kind: "tool-call",
            callId,
            toolName: "show_group_standings",
            input: { group: letter },
          },
        ],
        sequence: 2,
        stepIndex: 0,
        turnId,
      },
    },
    {
      type: "action.result",
      data: {
        result: {
          kind: "tool-result",
          callId,
          toolName: "show_group_standings",
          output: { group: `Group ${letter}` },
        },
        sequence: 3,
        stepIndex: 0,
        status: "completed",
        turnId,
      },
    },
    {
      type: "message.completed",
      data: {
        finishReason: "stop",
        message: answer,
        sequence: 4,
        stepIndex: 0,
        turnId,
      },
    },
    { type: "turn.completed", data: { sequence: 5, turnId } },
  ] as StreamEvent[];
}

function groupSeed(letter: GroupLetter): ForkSeed {
  return {
    events: groupEvents(letter),
    transcript:
      `User: How is group ${letter} going?\n\n` +
      `Assistant: Here is Group ${letter}: (showed the live Group ${letter} standings — ` +
      `current points, goal difference, and predicted finish for each team).`,
    createdAt: CREATED_AT,
  };
}

const slugOf = (letter: GroupLetter) => `group-${letter.toLowerCase()}`;

mkdirSync(OUT_DIR, { recursive: true });

const imports: string[] = [];
const entries: string[] = [];
for (const letter of groupLetters) {
  const slug = slugOf(letter);
  const file = new URL(`./group-${letter.toLowerCase()}.json`, OUT_DIR);
  writeFileSync(file, `${JSON.stringify(groupSeed(letter), null, 2)}\n`);
  const ident = `group${letter}`;
  imports.push(`import ${ident} from "./${slug}.json";`);
  entries.push(`  "${slug}": ${ident},`);
}

// A typed registry of the bundled seeds, served by loadFork as a fallback.
const index = `// Generated by lib/forks/seed-groups.ts — do not edit by hand.
import type { ForkSeed } from "../store";
${imports.join("\n")}

export const bundledSeeds = {
${entries.join("\n")}
} as unknown as Record<string, ForkSeed>;
`;
writeFileSync(new URL("./index.ts", OUT_DIR), index);

console.log(
  `Wrote ${groupLetters.length} group seeds + index to lib/forks/seeds/`,
);
