// Generated by lib/forks/seed-groups.ts — do not edit by hand.
import type { ForkSeed } from "../store";
import groupA from "./group-a.json";
import groupB from "./group-b.json";
import groupC from "./group-c.json";
import groupD from "./group-d.json";
import groupE from "./group-e.json";
import groupF from "./group-f.json";
import groupG from "./group-g.json";
import groupH from "./group-h.json";
import groupI from "./group-i.json";
import groupJ from "./group-j.json";
import groupK from "./group-k.json";
import groupL from "./group-l.json";

export const bundledSeeds = {
  "group-a": groupA,
  "group-b": groupB,
  "group-c": groupC,
  "group-d": groupD,
  "group-e": groupE,
  "group-f": groupF,
  "group-g": groupG,
  "group-h": groupH,
  "group-i": groupI,
  "group-j": groupJ,
  "group-k": groupK,
  "group-l": groupL,
} as unknown as Record<string, ForkSeed>;
